### ISSUE TITLE
TFD issues (follow-up from libgdx repo)

### ISSUE THREAD

**Issue by tommyettinger** [libgdx/gdx-particle-editor#3] opened 2023-11-27 04:48 UTC
I'm trying to move the conversation with @wangdong20 here, let's see how that goes. TFD is one of a few options out there for native file dialogs; GDX-Liftoff uses NFD 3.3.1, which is (also?) part of LWJGL3, and hasn't been buggy for me. That said, NFD 3.3.2 and later have been quite buggy on Linux, so I stick to 3.3.1 .

Using NFD is a little hairy, unfortunately, and the only example I have was written by Lyze, but here it is https://github.com/tommyettinger/gdx-liftoff/blob/76378fad691aa3b8575c9377cc18444f63ff1105/src/main/kotlin/gdx/liftoff/views/MainView.kt#L132-L170

Just something to consider if you continue to find problems with TFD!

**Comment by raeleus** [comment] 2023-11-27 04:58
I was running NFD before, but it has unique problems of its own. I really don't want to go back to using it, but I will if it's truly the lesser of two evils. Thanks @tommyettinger.

**Comment by raeleus** [comment] 2023-11-30 15:23
So far, I haven't been able to get any other mac users to reproduce this issue. I'll wait and see if more can test.

**Comment by raeleus** [comment] 2023-12-20 07:33
Since I can't get anyone else to reproduce, I'm going to close this. Feel free to open again if we can get someone active who can reproduce this reliably.

**Closed as completed by raeleus** 2023-12-20 07:33 UTC
